# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import problem_pb2 as problem__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in problem_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProblemServiceStub(object):
    """Service definition for problem-service gRPC API.
    Used internally by judge-standard for high-speed test case retrieval.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProblem = channel.unary_unary(
                '/problem.v1.ProblemService/GetProblem',
                request_serializer=problem__pb2.GetProblemRequest.SerializeToString,
                response_deserializer=problem__pb2.ProblemResponse.FromString,
                _registered_method=True)
        self.GetTestCases = channel.unary_unary(
                '/problem.v1.ProblemService/GetTestCases',
                request_serializer=problem__pb2.GetTestCasesRequest.SerializeToString,
                response_deserializer=problem__pb2.TestCasesResponse.FromString,
                _registered_method=True)
        self.ListProblems = channel.unary_unary(
                '/problem.v1.ProblemService/ListProblems',
                request_serializer=problem__pb2.ListProblemsRequest.SerializeToString,
                response_deserializer=problem__pb2.ListProblemsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/problem.v1.ProblemService/HealthCheck',
                request_serializer=problem__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=problem__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ProblemServiceServicer(object):
    """Service definition for problem-service gRPC API.
    Used internally by judge-standard for high-speed test case retrieval.
    """

    def GetProblem(self, request, context):
        """Get single problem by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTestCases(self, request, context):
        """Get test cases for a problem
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProblems(self, request, context):
        """List all problems (paginated)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check for gRPC
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProblemServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProblem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProblem,
                    request_deserializer=problem__pb2.GetProblemRequest.FromString,
                    response_serializer=problem__pb2.ProblemResponse.SerializeToString,
            ),
            'GetTestCases': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTestCases,
                    request_deserializer=problem__pb2.GetTestCasesRequest.FromString,
                    response_serializer=problem__pb2.TestCasesResponse.SerializeToString,
            ),
            'ListProblems': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProblems,
                    request_deserializer=problem__pb2.ListProblemsRequest.FromString,
                    response_serializer=problem__pb2.ListProblemsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=problem__pb2.HealthCheckRequest.FromString,
                    response_serializer=problem__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'problem.v1.ProblemService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('problem.v1.ProblemService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProblemService(object):
    """Service definition for problem-service gRPC API.
    Used internally by judge-standard for high-speed test case retrieval.
    """

    @staticmethod
    def GetProblem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/problem.v1.ProblemService/GetProblem',
            problem__pb2.GetProblemRequest.SerializeToString,
            problem__pb2.ProblemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTestCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/problem.v1.ProblemService/GetTestCases',
            problem__pb2.GetTestCasesRequest.SerializeToString,
            problem__pb2.TestCasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProblems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/problem.v1.ProblemService/ListProblems',
            problem__pb2.ListProblemsRequest.SerializeToString,
            problem__pb2.ListProblemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/problem.v1.ProblemService/HealthCheck',
            problem__pb2.HealthCheckRequest.SerializeToString,
            problem__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
