"""Constants used across the contest-service."""

# Default pagination
DEFAULT_SKIP = 0
DEFAULT_LIMIT = 10
MAX_LIMIT = 100

# Verdicts
VERDICT_ACCEPTED = "AC"
VERDICT_WRONG_ANSWER = "WA"
VERDICT_TIME_LIMIT = "TLE"
VERDICT_MEMORY_LIMIT = "MLE"
VERDICT_RUNTIME_ERROR = "RE"
VERDICT_COMPILATION_ERROR = "CE"

ALL_VERDICTS = {
    VERDICT_ACCEPTED,
    VERDICT_WRONG_ANSWER,
    VERDICT_TIME_LIMIT,
    VERDICT_MEMORY_LIMIT,
    VERDICT_RUNTIME_ERROR,
    VERDICT_COMPILATION_ERROR,
}
